# Generated by Django 3.2.3 on 2021-05-18 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(choices=[('DE', 'Dell'), ('AS', 'Asus'), ('MA', 'Mac'), ('AC', 'Acer')], max_length=2)),
                ('core', models.CharField(choices=[('Intel', (('I9', 'Intel Core I9'), ('I7', 'Intel Core I7'), ('I5', 'Intel Core I5'), ('I3', 'Intel Core I3'))), ('Amd', (('R9', 'AMD Ryzen 9'), ('R7', 'AMD Ryzen 7'), ('R5', 'AMD Ryzen 5'), ('R3', 'AMD Ryzen 3')))], max_length=2)),
                ('ram', models.CharField(choices=[('04', '4gb'), ('08', '8gb'), ('16', '16gb'), ('32', '32gb')], max_length=2)),
                ('hardware', models.CharField(choices=[('05', '500gb'), ('10', '1T')], max_length=2)),
                ('price', models.DecimalField(decimal_places=2, max_digits=99)),
                ('amount', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
