# Generated by Django 3.2.3 on 2021-05-19 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_list_computer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='list_computer',
            field=models.JSONField(),
        ),
    ]
